### ISSUE TITLE
Build on macOS 10.13 fails.

### ISSUE THREAD

**Issue by aryan9600** [microsoft/snmalloc#275]
I tried building snmalloc from source using the following commands
```
mkdir build
cd build
cmake -G Ninja .. -D CMAKE_BUILD_TYPE=Debug -D CMAKE_C_COMPILER=/usr/local/bin/gcc-10
ninja
```

The full traceback:
```
[1/170] Building CXX object CMakeFiles/func-two_alloc_types-malloc.dir/src/test/func/two_alloc_types/main.cc.o
FAILED: CMakeFiles/func-two_alloc_types-malloc.dir/src/test/func/two_alloc_types/main.cc.o 
/Library/Developer/CommandLineTools/usr/bin/c++  -DBACKTRACE_HEADER=\"execinfo.h\" -DSNMALLOC_PASS_THROUGH -DUSE_POSIX_COMMIT_CHECKS -DUSE_SNMALLOC_STATS -I../src -g   -Wsign-conversion -Wall -Wextra -Werror -Wundef -fno-exceptions -fno-rtti -g -fomit-frame-pointer -ftls-model=initial-exec -mcx16 -std=gnu++17 -MD -MT CMakeFiles/func-two_alloc_types-malloc.dir/src/test/func/two_alloc_types/main.cc.o -MF CMakeFiles/func-two_alloc_types-malloc.dir/src/test/func/two_alloc_types/main.cc.o.d -o CMakeFiles/func-two_alloc_types-malloc.dir/src/test/func/two_alloc_types/main.cc.o -c ../src/test/func/two_alloc_types/main.cc
In file included from ../src/test/func/two_alloc_types/main.cc:1:
In file included from ../src/test/func/two_alloc_types/../../../snmalloc.h:3:
In file included from ../src/mem/threadalloc.h:3:
In file included from ../src/mem/../ds/helpers.h:3:
../src/mem/../ds/bits.h:81:26: error: constexpr if condition is not a constant expression
      else if constexpr (std::is_same_v<unsigned long long, std::size_t>)
                         ^
../src/mem/../ds/bits.h:85:26: error: constexpr if condition is not a constant expression
      else if constexpr (std::is_same_v<unsigned int, std::size_t>)
                         ^
../src/mem/../ds/bits.h:162:26: error: constexpr if condition is not a constant expression
      else if constexpr (std::is_same_v<unsigned long long, std::size_t>)
                         ^
../src/mem/../ds/bits.h:166:26: error: constexpr if condition is not a constant expression
      else if constexpr (std::is_same_v<unsigned int, std::size_t>)
                         ^
4 errors generated.
[2/170] Building CXX object CMakeFiles/func-two_alloc_types-malloc.dir/src/test/func/two_alloc_types/alloc1.cc.o
FAILED: CMakeFiles/func-two_alloc_types-malloc.dir/src/test/func/two_alloc_types/alloc1.cc.o 
/Library/Developer/CommandLineTools/usr/bin/c++  -DBACKTRACE_HEADER=\"execinfo.h\" -DSNMALLOC_PASS_THROUGH -DUSE_POSIX_COMMIT_CHECKS -DUSE_SNMALLOC_STATS -I../src -g   -Wsign-conversion -Wall -Wextra -Werror -Wundef -fno-exceptions -fno-rtti -g -fomit-frame-pointer -ftls-model=initial-exec -mcx16 -std=gnu++17 -MD -MT CMakeFiles/func-two_alloc_types-malloc.dir/src/test/func/two_alloc_types/alloc1.cc.o -MF CMakeFiles/func-two_alloc_types-malloc.dir/src/test/func/two_alloc_types/alloc1.cc.o.d -o CMakeFiles/func-two_alloc_types-malloc.dir/src/test/func/two_alloc_types/alloc1.cc.o -c ../src/test/func/two_alloc_types/alloc1.cc
In file included from ../src/test/func/two_alloc_types/alloc1.cc:9:
In file included from ../src/test/func/two_alloc_types/../../../override/malloc.cc:1:
In file included from ../src/test/func/two_alloc_types/../../../override/../mem/slowalloc.h:1:
In file included from ../src/test/func/two_alloc_types/../../../override/../mem/globalalloc.h:3:
In file included from ../src/test/func/two_alloc_types/../../../override/../mem/../ds/helpers.h:3:
../src/test/func/two_alloc_types/../../../override/../mem/../ds/bits.h:81:26: error: constexpr if condition is not a constant expression
      else if constexpr (std::is_same_v<unsigned long long, std::size_t>)
                         ^
../src/test/func/two_alloc_types/../../../override/../mem/../ds/bits.h:85:26: error: constexpr if condition is not a constant expression
      else if constexpr (std::is_same_v<unsigned int, std::size_t>)
                         ^
../src/test/func/two_alloc_types/../../../override/../mem/../ds/bits.h:162:26: error: constexpr if condition is not a constant expression
      else if constexpr (std::is_same_v<unsigned long long, std::size_t>)
                         ^
../src/test/func/two_alloc_types/../../../override/../mem/../ds/bits.h:166:26: error: constexpr if condition is not a constant expression
      else if constexpr (std::is_same_v<unsigned int, std::size_t>)
                         ^
4 errors generated.
[3/170] Building CXX object CMakeFiles/func-two_alloc_types-malloc.dir/src/test/func/two_alloc_types/alloc2.cc.o
FAILED: CMakeFiles/func-two_alloc_types-malloc.dir/src/test/func/two_alloc_types/alloc2.cc.o 
/Library/Developer/CommandLineTools/usr/bin/c++  -DBACKTRACE_HEADER=\"execinfo.h\" -DSNMALLOC_PASS_THROUGH -DUSE_POSIX_COMMIT_CHECKS -DUSE_SNMALLOC_STATS -I../src -g   -Wsign-conversion -Wall -Wextra -Werror -Wundef -fno-exceptions -fno-rtti -g -fomit-frame-pointer -ftls-model=initial-exec -mcx16 -std=gnu++17 -MD -MT CMakeFiles/func-two_alloc_types-malloc.dir/src/test/func/two_alloc_types/alloc2.cc.o -MF CMakeFiles/func-two_alloc_types-malloc.dir/src/test/func/two_alloc_types/alloc2.cc.o.d -o CMakeFiles/func-two_alloc_types-malloc.dir/src/test/func/two_alloc_types/alloc2.cc.o -c ../src/test/func/two_alloc_types/alloc2.cc
In file included from ../src/test/func/two_alloc_types/alloc2.cc:10:
In file included from ../src/test/func/two_alloc_types/../../../override/malloc.cc:1:
In file included from ../src/test/func/two_alloc_types/../../../override/../mem/slowalloc.h:1:
In file included from ../src/test/func/two_alloc_types/../../../override/../mem/globalalloc.h:3:
In file included from ../src/test/func/two_alloc_types/../../../override/../mem/../ds/helpers.h:3:
../src/test/func/two_alloc_types/../../../override/../mem/../ds/bits.h:81:26: error: constexpr if condition is not a constant expression
      else if constexpr (std::is_same_v<unsigned long long, std::size_t>)
                         ^
../src/test/func/two_alloc_types/../../../override/../mem/../ds/bits.h:85:26: error: constexpr if condition is not a constant expression
      else if constexpr (std::is_same_v<unsigned int, std::size_t>)
                         ^
../src/test/func/two_alloc_types/../../../override/../mem/../ds/bits.h:162:26: error: constexpr if condition is not a constant expression
      else if constexpr (std::is_same_v<unsigned long long, std::size_t>)
                         ^
../src/test/func/two_alloc_types/../../../override/../mem/../ds/bits.h:166:26: error: constexpr if condition is not a constant expression
      else if constexpr (std::is_same_v<unsigned int, std::size_t>)
                         ^
4 errors generated.
ninja: build stopped: subcommand failed.
```

```
gcc --version
gcc-10 (Homebrew GCC 10.2.0) 10.2.0
```
```
cmake --version
cmake version 3.17.3
```
```
Operating System: macOS 10.13.6
```

**Comment by davidchisnall** [comment]
macOS 10.13 is unsupported by Apple as of December 2020 and no longer receiving security updates so I would strongly recommend against continuing to use it.  

This problem appears to be a problem coming from the version of clang and the C++ standard library that you're using.  This is not something that we can easily fix in snmalloc, because your combination of C++ standard library and compiler are claiming something is not a constant that the standard requires to be a constant.  That was a bug in old versions of Apple developer tools, but is fixed on all of the versions that Apple supports.

From the command-line invocation, it doesn't look as if you're actually building with gcc (`/Library/Developer/CommandLineTools/usr/bin/c++` is clang).  If you want to use gcc, then you need to add this to your cmake invocation: ` -D CMAKE_CXX_COMPILER=/usr/local/bin/g++-10`.

**Comment by mjp41** [comment]
Previously, we had [worked around](https://github.com/microsoft/snmalloc/pull/244) this issue with `std::is_same(...)::value`, but I guess recent updates have regressed that fix.

**Comment by davidchisnall** [comment]
I don't think we merged that PR, the author just updated his CI to a vaguely recent XCode that doesn't have this bug and closed it.

**Comment by mjp41** [comment]
@davidchisnall you are correct.  So the code does use some `std::is_same<...>::value` and some `std::is_same_v<...>`. I would be happy to make the code consistently use `std::is_same<...>::value`.  

@aryan9600  if fixing the command line to use GCC from Brew doesn't fix it, and you are not able to upgrade to a more recent version, then I would be happy to take a rewrite to `std::is_same<...>::value`.  But this is likely to be broken as nothing would enforce this usage in CI.  So you may have to submit PRs if we break it in the future.

**Comment by aryan9600** [comment]
@mjp41 @davidchisnall instructing cmake to use g++-10 works. thanks for the help.
