### ISSUE TITLE
MSVC ARM64 internal compiler error when building static shim on Windows ARM64

### ISSUE THREAD

**Issue by xiaozhuai** [microsoft/snmalloc#862]
## Description

When updating snmalloc to 0.7.5 in vcpkg https://github.com/microsoft/vcpkg/pull/52545, the arm64-windows CI job fails while building the static-shim feature.

The failure happens when compiling the static shim targets, such as snmalloc-new-override / snmallocshim-static, with MSVC targeting ARM64 in Release mode.

The default header-only build does not appear to be affected. The issue seems specific to the compiled static shim path enabled by `SNMALLOC_STATIC_LIBRARY`.

## Error

The build fails with an MSVC internal compiler error:

```
freelist.h(917) : Illegal reg field
fatal error C1001: Internal compiler error.
compiler file '...\p2\arm64\disencode.cpp'
```

## Environment
Platform: Windows ARM64
Compiler: MSVC
Build type: Release
Package manager: vcpkg
snmalloc version: 0.7.5
Feature: static-shim

## Observed behavior

Building the static-shim feature on arm64-windows fails with an MSVC ARM64 backend internal compiler error.

## Expected behavior

The static shim targets should compile successfully on Windows ARM64, or the unsupported compiler/architecture combination should be documented or guarded.

**Comment by mjp41** [comment]
Which precise version of MSVC are you using.  When I tried to repro with 14.51.36231 it compiled fine.

**Comment by xiaozhuai** [comment]
> Which precise version of MSVC

I'm also using `14.51.36231`. It can repro when build **release** type. Some compiler optimization cause an ICE.

**Comment by mjp41** [comment]
Sorry for the delay.  I can locally replicate this.  

I have submitted a issue against VS.
https://developercommunity.visualstudio.com/t/MSVC-ARM64-compile-hits-C1001-Internal-C/11126607

I am not keen to randomly change code to work around a compiler bug.
